# .github/workflows/update_subscription.yml
name: Update Clash Subscription

on:
  workflow_dispatch:   # 手动触发，方便测试
  schedule:
    - cron: '0 16 * * *'    # UTC+8 00:00
    - cron: '0 4 * * *'     # UTC+8 12:00

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "✅ Workflow is running!"
