name: Update Clash Subscription

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
    - cron: '0 4 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests PyYAML

      - name: Create scripts/update_subscription.py
        run: |
          mkdir -p scripts
          cat > scripts/update_subscription.py << 'EOF'
#!/usr/bin/env python3
import os
from pathlib import Path
import yaml

ROOT = Path('.').resolve()
OUTPUT_FILE = ROOT / 'subscription.yaml'

# 最小可运行示例
subscription = {
    'proxies': [],
    'proxy-groups': [],
    'rules': ['MATCH,DIRECT']
}

OUTPUT_FILE.write_text(yaml.safe_dump(subscription, allow_unicode=True, sort_keys=False))
print(f"[SUCCESS] wrote {OUTPUT_FILE}")
EOF

      - name: Run update script
        run: |
          python scripts/update_subscription.py

      - name: Show top of subscription.yaml
        run: |
          head -n 20 subscription.yaml || true

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add subscription.yaml || true
          git commit -m "自动更新订阅 $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git pull --rebase origin "$BRANCH" || true
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:"$BRANCH"
