# .github/workflows/update_subscription.yml
name: Update Clash Subscription

on:
  workflow_dispatch:   # 手动触发按钮
  schedule:
    - cron: "0 16 * * *"    # 每天 UTC 16 点
    - cron: "0 4 * * *"     # 每天 UTC 4 点

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "✅ Workflow is running!"
