name: Update Clash Subscription

on:
  schedule:
    - cron: '0 16 * * *'    # UTC 16:00 -> UTC+8 00:00
    - cron: '0 4 * * *'     # UTC 04:00 -> UTC+8 12:00
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 确保能获取完整历史，避免 rebase 出问题

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML dnspython pysocks

      - name: Run update script
        env:
          SOURCE_URLS: ${{ secrets.SOURCE_URLS }}
          PREFERRED_IP_REPO: https://raw.githubusercontent.com/ethgan/yxip/main/ip.txt
          KEEP_NODES: '200'
          MAX_FINAL: '50'
        run: |
          python scripts/update_subscription.py

      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add subscription.yaml
          git commit -m "自动更新订阅 $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git pull --rebase origin main   # 关键步骤：先同步远程最新提交
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
